# yaml-language-server: $schema=https://www.schemastore.org/pnpm-workspace.json

allowBuilds:
  esbuild: true
  lefthook: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@oxfmt/binding-android-arm-eabi'
  - '@oxfmt/binding-android-arm64'
  - '@oxfmt/binding-darwin-arm64'
  - '@oxfmt/binding-darwin-x64'
  - '@oxfmt/binding-freebsd-x64'
  - '@oxfmt/binding-linux-arm-gnueabihf'
  - '@oxfmt/binding-linux-arm-musleabihf'
  - '@oxfmt/binding-linux-arm64-gnu'
  - '@oxfmt/binding-linux-arm64-musl'
  - '@oxfmt/binding-linux-ppc64-gnu'
  - '@oxfmt/binding-linux-riscv64-gnu'
  - '@oxfmt/binding-linux-riscv64-musl'
  - '@oxfmt/binding-linux-s390x-gnu'
  - '@oxfmt/binding-linux-x64-gnu'
  - '@oxfmt/binding-linux-x64-musl'
  - '@oxfmt/binding-openharmony-arm64'
  - '@oxfmt/binding-win32-arm64-msvc'
  - '@oxfmt/binding-win32-ia32-msvc'
  - '@oxfmt/binding-win32-x64-msvc'
  - '@oxlint/binding-android-arm-eabi'
  - '@oxlint/binding-android-arm64'
  - '@oxlint/binding-darwin-arm64'
  - '@oxlint/binding-darwin-x64'
  - '@oxlint/binding-freebsd-x64'
  - '@oxlint/binding-linux-arm-gnueabihf'
  - '@oxlint/binding-linux-arm-musleabihf'
  - '@oxlint/binding-linux-arm64-gnu'
  - '@oxlint/binding-linux-arm64-musl'
  - '@oxlint/binding-linux-ppc64-gnu'
  - '@oxlint/binding-linux-riscv64-gnu'
  - '@oxlint/binding-linux-riscv64-musl'
  - '@oxlint/binding-linux-s390x-gnu'
  - '@oxlint/binding-linux-x64-gnu'
  - '@oxlint/binding-linux-x64-musl'
  - '@oxlint/binding-openharmony-arm64'
  - '@oxlint/binding-win32-arm64-msvc'
  - '@oxlint/binding-win32-ia32-msvc'
  - '@oxlint/binding-win32-x64-msvc'
  - knip@6.17.2
  - oxfmt
  - oxlint
