# yaml-language-server: $schema=https://www.schemastore.org/pnpm-workspace.json

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
  lefthook: true

verifyDepsBeforeRun: false

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@base-ui/react'
  - '@base-ui/utils'
  - '@types/react-dom'
  - '@vitest/browser'
  - '@vitest/browser-playwright'
  - '@vitest/coverage-v8'
  - '@vitest/mocker'
  - '@vitest/pretty-format'
  - '@vitest/spy'
  - '@vitest/ui'
  - '@vitest/utils'
  - happy-dom
  - knip
  - lucide-react
  - oxfmt
  - oxlint
  - vitest
